### ISSUE TITLE
CShuster feedback milestone3

### ISSUE THREAD

**Issue by shusterc** [UBC-MDS/DSCI_532_Wine_Betty_Milos#17]
- sidebar selectors working very well, I like that you can see the number above the sliders
- very nice that the table stays the same even when you switch the tabs
- the plots are very clear and easy to follow
- the table is easy to navigate and filter
- title could be improved to make it the use case more intuitive

overall great job!

**Comment by bettybhzhou** [comment]
Thanks for the feedback!
