### ISSUE TITLE
Feedback from Richie

### ISSUE THREAD

**Issue by rzitomer** [UBC-MDS/DSCI_532_Wine_Betty_Milos#18]
- For the table, I would have the name of the wine bottle be all the way to the left.
- Make it more clear what the search bar for the table is
- Really like the table - very clear what purpose it serves, nice filtering functionality
- Have a default sort on the table (or at least explain how its sorted now)
- Would be nice to have a writeup with some explanation of variables (for example, its not immediately obvious why the rating is between 80-100)

**Comment by bettybhzhou** [comment]
Thanks Richie for the feedback! we've implemented all your suggestions.
