### ISSUE TITLE
Feedback Milestone 1

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI_532_Wine_Betty_Milos#8]
-Overall your proposal is good but there is a bit of confusion about the goal. In the overview you state that this app would be some sort of template for liquor supply chains to develop their own, however, in the usage scenario you say it is for costumers (which is also not clearly defined what you mean by a costumer). 
-The sketch is nicely displayed, some examples of the data would've been great in the table and drop down menus. Is your table interactive? (e.g. you can arrange rows by a variable)
-How exactly are the inputs from the user reflected on the map?

**Comment by milicmil** [comment]
The scenario we described is the individual customer and the institutional customer(bar owner, restaurant owner etc.). In the case of LCBO, it is a quirk in Ontario that it is the only legal body that sells all types of alcohol thus all customers pretty much use the same tools to find drinks that they need to purchase. Our thought is that the same display and arrangement of information would be informative to an individual searching for a new bottle of merlot as it would be for the restaurant owner looking to spruce up their wine list.

**Comment by milicmil** [comment]
We decided not to implement the map initially.
